In [1]:
# NumPy Ndarray
# Creating a NumPy Array

import numpy as np
np.__version__

'1.18.5'

In [2]:
arr=np.array([1,2,3])  
print(arr)
print(type(arr))

[1 2 3]
<class 'numpy.ndarray'>


In [3]:
# shape attribute
# returns shape of an array
# For 1D shape returns (n,)
# where n is the number of elements in an Array
# For 2D shape returns(n,m)
# where n is the number of row
# and m is the column

print(arr.shape)

(3,)


In [4]:
# More than one dimensions
import numpy as np  
arr=np.array([[1,2,3],[4,5,7]])  
print(arr)

[[1 2 3]
 [4 5 7]]


In [6]:
print(arr.shape)

(3, 2)


In [8]:
# Creating 3X2 Array
import numpy as np  
arr=np.array([[1,2],[3,4],[5,6]])  
print(arr)  

[[1 2]
 [3 4]
 [5 6]]


In [9]:
# NumPy Array Indexing

arr = np.array([1, 2, 3, 4])
print(arr[0])
print(arr[-1])

1
4


In [10]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('2nd element on 1st row: ', arr[0, 1])

2nd element on 1st row:  2


In [12]:
# NumPy Array Slicing
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])
print(arr[4:])
print(arr[:4])
print(arr[-3:-1])

[2 3 4 5]
[5 6 7]
[1 2 3 4]
[5 6]


In [13]:
# Iteration Using For Loop
for i in arr:
    print(i)

1
2
3
4
5
6
7


In [14]:
# Iteration Along With Index Numbers
for i in range(len(arr)):
    print('Index',i,':',arr[i])

Index 0 : 1
Index 1 : 2
Index 2 : 3
Index 3 : 4
Index 4 : 5
Index 5 : 6
Index 6 : 7


In [15]:
# Numpy Data Types
arr = np.array([1, 2, 3, 4])
print(arr.dtype)

int32


In [16]:
arr = np.array(['apple', 'banana', 'cherry'])
print(arr.dtype)

<U6


In [18]:
arr = np.array([1, 2, 3, 4], dtype='i4')
print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [19]:
arr = np.array([1, 2, 3, 4], dtype='i8')
print(arr)
print(arr.dtype)

[1 2 3 4]
int64


In [20]:
# Converting Data Type on Existing Arrays
arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype('i')
print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [22]:
# NumPy Array Copy vs View
# copy
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
print(x)

[1 2 3 4 5]


In [23]:
# Let's make some changes in original array
arr[0] = 42
print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [24]:
# View
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
print(x)

[1 2 3 4 5]


In [25]:
# Let's make some changes in original array
arr[0] = 42
print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [26]:
# Make Changes in the VIEW
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 31
print(arr)
print(x)

[31  2  3  4  5]
[31  2  3  4  5]


In [27]:
# NumPy Array Reshaping
# Reshape From 1-D to 2-D
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [28]:
# Reshape From 2-D to 1-D
arr=np.array([[1,2],[3,4],[5,6]])
newarr = arr.reshape(6)
print(newarr)

[1 2 3 4 5 6]


In [29]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
newarr = arr.reshape(-1)
print(newarr)

[1 2 3 4 5 6]


In [30]:
# Filter a Numpy Array
arr = np.array([1, 4, 2, 7, 9, 3, 5, 8])
print(arr)

[1 4 2 7 9 3 5 8]


In [31]:
# boolean mask of elements to keep
mask = arr > 5
print(mask)

[False False False  True  True False False  True]


In [32]:
# filter the array
arr_filtered = arr[mask]
# show the filtered array
print(arr_filtered)

[7 9 8]


In [35]:
arr = np.array([1, 4, 2, 7, 9, 3, 5, 8])
indexes_to_keep = np.where(arr > 5)
print(indexes_to_keep)
# np.where() gives IndexNumber In output

(array([3, 4, 7], dtype=int64),)


In [36]:
arr_filtered = arr[indexes_to_keep]
# show the filtered array
print(arr_filtered)

[7 9 8]


In [37]:
# Filter array based on two conditions
filtered_arr = arr[(arr > 5) & (arr < 9)]
print(filtered_arr)

[7 8]


In [38]:
# Join two arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [39]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2))

print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [40]:
# Array Split
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [41]:
print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


In [43]:
# Searching Arrays
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

# value 4 is present at index 3, 5, and 6.

(array([3, 5, 6], dtype=int64),)


In [44]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x)

(array([1, 3, 5, 7], dtype=int64),)


In [51]:
# Sorting Arrays
arr = np.array([3, 2, 0, 1 , 6 , 5])

print(np.sort(arr))

# This method returns a copy of the array, leaving the original array
# unchanged.

[0 1 2 3 5 6]


In [52]:
print(arr)

[3 2 0 1 6 5]


In [53]:
# Sort NumPy Array in decreasing order
arr = np.sort(arr)[::-1]
print(arr)

[6 5 3 2 1 0]


In [54]:
# Numpy Random
from numpy import random

x = random.randint(100)

print(x)

52


In [55]:
# Generate Random Float
# The random module's rand() method returns a random float between 0 and 1.

x = random.rand()

print(x)

0.09267498721205858


In [57]:
x=random.randint(100, size=(5))
print(x)

# Generate Random Number Uptill 100

[43 18 72 77 51]


In [58]:
x = random.randint(100, size=(3, 5))
print(x)

[[61 61 81 11  1]
 [89 45 43 86 90]
 [83 49 26 31 90]]


In [59]:
x = random.rand(3, 5)

print(x)

[[8.80190462e-01 5.28408536e-01 5.28692613e-01 4.15126435e-01
  4.63773919e-01]
 [2.62334117e-01 3.12556874e-01 5.22814222e-01 9.17896033e-01
  2.36492452e-01]
 [3.61513867e-01 9.16846264e-04 8.57751220e-01 2.96541584e-02
  9.73691735e-01]]


In [62]:
# The choice() method allows you to generate a random value 
# based on an array of values.

x = random.choice([3, 5, 7, 9])

print(x)

7


In [63]:
x = random.choice([3, 5, 7, 9], size=(3, 5))

print(x)

[[9 5 7 5 9]
 [7 5 7 3 7]
 [7 5 9 7 3]]


In [64]:
# Numpy Functions
# numpy.zeros()
# This function is used to generate an array containing zeros.

a=np.zeros(6)  
a

array([0., 0., 0., 0., 0., 0.])

In [66]:
a=np.zeros((6), dtype=int)  
a

array([0, 0, 0, 0, 0, 0])

In [67]:
# numpy.ones()
# This function is used to generate an array containing ones.
a=np.ones((6,2))  
a  

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [68]:
a=np.ones((6,2),dtype=int)  
a 

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [69]:
# numpy.sum()
#  This function is used to compute the sum of all elements
x = random.randint(50, size=(3, 5))
s = np.sum(x)  
s  

408

In [72]:
# numpy.unique()
a=np.unique([1,2,3,4,9,10,9,3,6,2,4])  
a

# returns unique elements as a sorted array

array([ 1,  2,  3,  4,  6,  9, 10])

In [73]:
# arange()
print(np.arange(4).reshape(2, 2))
print(np.arange(4, 10))
print(np.arange(4, 20, 3))

[[0 1]
 [2 3]]
[4 5 6 7 8 9]
[ 4  7 10 13 16 19]


In [74]:
# Numpy Broadcasting
a = np.array([1.0, 2.0, 3.0])
b = np.array([2.0, 2.0, 2.0])
a * b

array([2., 4., 6.])

In [75]:
a = np.array([1.0, 2.0, 3.0])
b = np.array([2.0, 2.0])
a * b

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [76]:
a = np.array([1, 2, 3])
b = np.array([2])
a * b

array([2, 4, 6])